### ISSUE TITLE
您好，为什么ipid配置删除了？

### ISSUE THREAD

**Issue by Rain021300** [IYATT-yx/Router#2]
您好，最近也在研究校园网固件，前几天发现您的博客更新记录里还有ipid配置，目前（9.21）发现已经被删除，是已经用不到了吗？

**Comment by Rain021300** [comment]
并且还想问一下：   
 修改了 lede/package/base-files/files/etc/rc.local，将防 UA2F、TTL、NTP、FLASH 检测相关的防火墙配置预写入系统，不再需要刷机后手动设置，做到开箱即用
    修改了 lede/package/lean/default-settings/files/zzz-default-settings（lede 的默认设置文件），去除了 lede 的默认密码（留空），将 UA2F 首次启用相关命令写入，不再需要刷机后手动执行，做到开箱即用
    去掉了部分默认勾选编译的应用（我认为用不上的），另外添加了应用，最终编译的应用如图：

这部分可以详细写出来吗，本人非科班出身，只是对计算机有兴趣，希望您可以写的详细一点，谢谢！

**Comment by IYATT-yx** [comment]
> 并且还想问一下： 修改了lede/package/base-files/files/etc/rc.local，将防UA2F、TTL、NTP、FLASH检测相关的故障配置预写系统，不再需要刷机后手动设置，开箱即用修改了 lede /package/lean/default-settings/files/zzz-default-settings（lede 的默认设置文件），去除了 lede 的默认密码（留空），将 UA2F 首次启用写入，不再需要刷机后手动执行，完成开箱即用删除 部分默认勾选编译的应用（我认为是上的），另外应用，最终编译的应用不添加显示：
> 
> 这部分可以详细写出来吗，本人非科班出身，只是对计算机有兴趣，希望您可以详细写出一点，谢谢！

不需要配置这部分，新版本的 UA2F 直接启用会自动配置

**Comment by IYATT-yx** [comment]
> 您好，最近发现应用研究网发现，已经记录前几天您的博客里还有ipid配置被删除，（9.21），是已经不到用了吗？

用不上，所以就去掉了

**Comment by Rain021300** [comment]
> 

为什么呢？对于你学校防检测没有作用吗？

**Comment by IYATT-yx** [comment]
> > 
> 
> 为什么呢？对于你学校防检测没有作用吗？

对的，目前测试情况，应该是没有这种检测方式的。

**Comment by Rain021300** [comment]
> 

目前我的学校跟你学校的应该差不多，你可以试一下使用mentohust进行认证，需要填写锐捷版本号（由于我不知道我学校的锐捷是什么时候启用的，所以我填写的是4.92，你也可以试试）。之前我没有使用mentohust进行认证，会经常检测出网络共享，也可能是设备过多的原因，但是我现在使用mentohust进行认证，被检测的频率大大降低（大概十天半个月才会被检测一次）。上学期经过网络改造后，被检测会被封禁账号，不允许登录，这一点是跟你的学校是一样的，之前只会提示设备共享，但是更换路由器wan口mac地址就可以再次登录。以上是我的经历，希望可以给你带来帮助。

**Comment by IYATT-yx** [comment]
> > 
> 
> 目前我的学校跟你学校的应该差不多，你可以试一下使用mentohust进行认证，需要填写锐捷版本号（由于我不知道我学校的锐捷是什么时候启用的，所以我填写的是4.92，你也可以试试）。之前我没有使用mentohust进行认证，会经常检测出网络共享，也可能是设备过多的原因，但是我现在使用mentohust进行认证，被检测的频率大大降低（大概十天半个月才会被检测一次）。上学期经过网络改造后，被检测会被封禁账号，不允许登录，这一点是跟你的学校是一样的，之前只会提示设备共享，但是更换路由器wan口mac地址就可以再次登录。以上是我的经历，希望可以给你带来帮助。

我们学校的是 Web 认证，没有客户端。路由器WAN设置DHCP，手机或电脑连路由器登录就行。只需要防止被检测出来就行。

**Comment by Rain021300** [comment]
> > > 
> > 
> > 
> > 目前我的学校跟你学校的应该差不多，你可以试一下使用mentohust进行认证，需要填写锐捷版本号（由于我不知道我学校的锐捷是什么时候启用的，所以我填写的是4.92，你也可以试试）。之前我没有使用mentohust进行认证，会经常检测出网络共享，也可能是设备过多的原因，但是我现在使用mentohust进行认证，被检测的频率大大降低（大概十天半个月才会被检测一次）。上学期经过网络改造后，被检测会被封禁账号，不允许登录，这一点是跟你的学校是一样的，之前只会提示设备共享，但是更换路由器wan口mac地址就可以再次登录。以上是我的经历，希望可以给你带来帮助。
> 
> 我们学校的是 Web 认证，没有客户端。路由器WAN设置DHCP，手机或电脑连路由器登录就行。只需要防止被检测出来就行。

我的也是web认证，但是你可以换个思路使用mentohust进行认证，我在来我学校时候也问过，一直都是web认证，但是我使用路由器端mentohust（mentohust+luci-app-mentohust）也可以认证成功。你可以测试一下。

**Comment by IYATT-yx** [comment]
> > > > 
> > > 
> > > 
> > > 目前我的学校跟你学校的应该差不多，你可以试一下使用mentohust进行认证，需要填写锐捷版本号（由于我不知道我学校的锐捷是什么时候启用的，所以我填写的是4.92，你也可以试试）。之前我没有使用mentohust进行认证，会经常检测出网络共享，也可能是设备过多的原因，但是我现在使用mentohust进行认证，被检测的频率大大降低（大概十天半个月才会被检测一次）。上学期经过网络改造后，被检测会被封禁账号，不允许登录，这一点是跟你的学校是一样的，之前只会提示设备共享，但是更换路由器wan口mac地址就可以再次登录。以上是我的经历，希望可以给你带来帮助。
> > 
> > 
> > 我们学校的是 Web 认证，没有客户端。路由器WAN设置DHCP，手机或电脑连路由器登录就行。只需要防止被检测出来就行。
> 
> 我的也是web认证，但是你可以换个思路使用mentohust进行认证，我在来我学校时候也问过，一直都是web认证，但是我使用路由器端mentohust（mentohust+luci-app-mentohust）也可以认证成功。你可以测试一下。

你们学校的会对密码加密吗？

**Comment by Rain021300** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 目前我的学校跟你学校的应该差不多，你可以试一下使用mentohust进行认证，需要填写锐捷版本号（由于我不知道我学校的锐捷是什么时候启用的，所以我填写的是4.92，你也可以试试）。之前我没有使用mentohust进行认证，会经常检测出网络共享，也可能是设备过多的原因，但是我现在使用mentohust进行认证，被检测的频率大大降低（大概十天半个月才会被检测一次）。上学期经过网络改造后，被检测会被封禁账号，不允许登录，这一点是跟你的学校是一样的，之前只会提示设备共享，但是更换路由器wan口mac地址就可以再次登录。以上是我的经历，希望可以给你带来帮助。
> > > 
> > > 
> > > 我们学校的是 Web 认证，没有客户端。路由器WAN设置DHCP，手机或电脑连路由器登录就行。只需要防止被检测出来就行。
> > 
> > 
> > 我的也是web认证，但是你可以换个思路使用mentohust进行认证，我在来我学校时候也问过，一直都是web认证，但是我使用路由器端mentohust（mentohust+luci-app-mentohust）也可以认证成功。你可以测试一下。
> 
> 你们学校的会对密码加密吗？

我之前f12抓包好像发现是加密的，待会儿我再确定一下，目前我在写我的编译流程。你可以通过微信或者QQ联系我，主页有我的邮箱，搜索我的QQ就可以。

**Comment by Rain021300** [comment]
http://172.168.168.198/eportal/index.jsp?wlanuserip=59b6647a************************&wlanacname=2ed93**********************&ssid=&nasip=23233************************&snmpagentip=&mac=8623e4***************************&t=wireless-v2&url=8d188**************************&apmac=&nasid=2ed934**********************&vid=eac75b387**************************&nasportid=bf2334948***********************************************************

以上应该是发送的封包数据。

**Comment by IYATT-yx** [comment]
我用Padavan固件（含 MentHUST）配置连上了，QQ可以用，网页打不开，可能 DNS 有问题

**Comment by Rain021300** [comment]
> 我用Padavan固件（含 MentHUST）配置连上了，QQ可以用，网页打不开，可能 DNS 有问题

我之前也用的老毛子，刚才编译了份带mentohust的精简openwrt并按照教程配置了下放检测，要不明天我给你编译一份你的路由器固件试试？

**Comment by Rain021300** [comment]
你可以试一下这个大佬的固件https://pan.wwang.pw/
校园网文件夹如果有密码应该是hhao.cc。openwrt带mentohust（我是k2p测试的，别的不知道有没有），但是我不知道他的是原版的mentohust还是openwrt-mentohust，我也不清楚校园网固件做了哪方面的优化。

**Comment by IYATT-yx** [comment]
有点问题，我们学校的是两家运营商，有一个 service 参数指定，MentoHUST 没这个

**Comment by Rain021300** [comment]
> 有点问题，我们学校的是两家运营商，有一个 service 参数指定，MentoHUST 没这个

我学校电信 移动 联通都有，但是锐捷服务器只有一个呀，他们只是账号开通了登录权限。你可以尝试换一家运营商登录

**Comment by Rain021300** [comment]
你把封包数据发出来我看一下

**Comment by IYATT-yx** [comment]
userId、password、service、queryString、operatorPwd（空）、operatorUserId（空）、validcode（空）、passwordEncrypt（true），POST 的内容

**Comment by IYATT-yx** [comment]
> userId、password、service、queryString、operatorPwd（空）、operatorUserId（空）、validcode（空）、passwordEncrypt（true），POST 的内容

service 就是运营商

**Comment by Rain021300** [comment]
我回去宿舍看一下再联系你

**Comment by IYATT-yx** [comment]
> 我回去宿舍看一下再联系你

我准备弄脚本，用 curl POST

**Comment by Rain021300** [comment]
> > 我回去宿舍看一下再联系你
> 
> 我准备弄脚本，用 curl POST

我感觉这样做没用，你脚本在路由器上登录还是跟手动登录一样，都是使用路由器的设备。我建议你去看看openwrtmentohust和mentohust原版，我看不懂代码不能帮你。你昨天说用老毛子加上mentohust可以登陆那应该没有问题的，要不我编制一个固件你试试，目前在我这使用是没问题的

**Comment by IYATT-yx** [comment]
> > > 我回去宿舍看一下再联系你
> > 
> > 
> > 我准备弄脚本，用 curl POST
> 
> 我感觉这样做没用，你脚本在路由器上登录还是跟手动登录一样，都是使用路由器的设备。我建议你去看看openwrtmentohust和mentohust原版，我看不懂代码不能帮你。你昨天说用老毛子加上mentohust可以登陆那应该没有问题的，要不我编制一个固件你试试，目前在我这使用是没问题的

脚本那个是弄多拨的。MentoHUST 我编译到 OpenWrt 了，ping 测试能通也没丢包，但是网页打不开。

**Comment by Rain021300** [comment]
> > > > 我回去宿舍看一下再联系你
> > > 
> > > 
> > > 我准备弄脚本，用 curl POST
> > 
> > 
> > 我感觉这样做没用，你脚本在路由器上登录还是跟手动登录一样，都是使用路由器的设备。我建议你去看看openwrtmentohust和mentohust原版，我看不懂代码不能帮你。你昨天说用老毛子加上mentohust可以登陆那应该没有问题的，要不我编制一个固件你试试，目前在我这使用是没问题的
> 
> 脚本那个是弄多拨的。MentoHUST 我编译到 OpenWrt 了，ping 测试能通也没丢包，但是网页打不开。

//判断默认服务是否是电信服务
	  		    if(document.getElementById("isNoOperatorPasswordFrameId")&&is=='true'){
	  		    	 $("#operatorPwd_tip").attr("value","请输入"+document.getElementById("selectDisname").innerHTML+"对应的密码");
	  		   		 document.getElementById("isNoOperatorPasswordFrameId").style.display="block";
	  		   		 document.getElementById("isNoOperatorPasswordFrameId_space").style.display="block";
	  		   	}
	   	 	}
	   	 	//判断是否有服务可以选择
	   	 	if(service.isService&&service.isService=='false'){
	   	 		$("#isDisplayServicesTip").hide();
	  	 		$("#isDisplayServices").hide();
	   	 	}
	   	 	jqueryBind();
   	 	});
 	}
 	var successPage="";
 	var prefixValue="";
	function fillData(){
		    AuthInterFace.init("./");
		    AuthInterFace.pageInfo(encodeURIComponent(getQueryString()),function(pageInfo){
		    			successPage=pageInfo.successPage;
				    	AuthInterFace.getOnlineUserInfo('',function(online){
					    	 if(online&&online.result=='success'&&online.userIndex!=''){
					    		 if(successPage&&successPage!=''&&successPage=="true"){
					    			 window.location.href=online.userUrl;
					    		 }else{
					    			 window.location="success.jsp?userIndex="+online.userIndex;
					    		 }
						    }
			    		});


我在我学校登录页面源代码找到了这个，我学校的应该关了服务选择。你什么型号路由器，我给你编译一个固件你试试

**Comment by Rain021300** [comment]
你填写版本号了吗？

**Comment by IYATT-yx** [comment]
> > > > > 我回去宿舍看一下再联系你
> > > > 
> > > > 
> > > > 我准备弄脚本，用 curl POST
> > > 
> > > 
> > > 我感觉这样做没用，你脚本在路由器上登录还是跟手动登录一样，都是使用路由器的设备。我建议你去看看openwrtmentohust和mentohust原版，我看不懂代码不能帮你。你昨天说用老毛子加上mentohust可以登陆那应该没有问题的，要不我编制一个固件你试试，目前在我这使用是没问题的
> > 
> > 
> > 脚本那个是弄多拨的。MentoHUST 我编译到 OpenWrt 了，ping 测试能通也没丢包，但是网页打不开。
> 
> //判断默认服务是否是电信服务 if(document.getElementById("isNoOperatorPasswordFrameId")&&is=='true'){ $("#operatorPwd_tip").attr("value","请输入"+document.getElementById("selectDisname").innerHTML+"对应的密码"); document.getElementById("isNoOperatorPasswordFrameId").style.display="block"; document.getElementById("isNoOperatorPasswordFrameId_space").style.display="block"; } } //判断是否有服务可以选择 if(service.isService&&service.isService=='false'){ $("#isDisplayServicesTip").hide(); $("#isDisplayServices").hide(); } jqueryBind(); }); } var successPage=""; var prefixValue=""; function fillData(){ AuthInterFace.init("./"); AuthInterFace.pageInfo(encodeURIComponent(getQueryString()),function(pageInfo){ successPage=pageInfo.successPage; AuthInterFace.getOnlineUserInfo('',function(online){ if(online&&online.result=='success'&&online.userIndex!=''){ if(successPage&&successPage!=''&&successPage=="true"){ window.location.href=online.userUrl; }else{ window.location="success.jsp?userIndex="+online.userIndex; } } });
> 
> 我在我学校登录页面源代码找到了这个，我学校的应该关了服务选择。你什么型号路由器，我给你编译一个固件你试试

MediaTek Ralink MIPS - MT7621 based boards - Xiaomi Redmi Router AC2100

**Comment by IYATT-yx** [comment]
> 你填写版本号了吗？

填了的

**Comment by Rain021300** [comment]
我去编译一份

**Comment by Rian-l** [comment]
「自编译固件」https://www.aliyundrive.com/s/qJNREBNsBwW
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

**Comment by IYATT-yx** [comment]
> 我去编译一份

感谢

**Comment by Rain021300** [comment]
稍等我下，我现在这边网络出了bug

**Comment by Rain021300** [comment]
我用夸克网盘分享了「redmi ac2100」，点击链接即可保存。打开「夸克APP」，无需下载在线播放视频，畅享原画5倍速，支持电视投屏。
链接：https://pan.quark.cn/s/d86d7fa5b581

**Comment by Rain021300** [comment]
有可能有bug 晚点我再同步下源码再编制一下，刚才突然卡死进不去路由器全部断网

**Comment by IYATT-yx** [comment]
emmm,还是一样的

**Comment by Rain021300** [comment]
> emmm,还是一样的

组播地址选锐捷，dhcp选认证后，接口选eth1

**Comment by Rain021300** [comment]
版本号4.92

**Comment by Rain021300** [comment]
这是我的配置，你再试一下

**Comment by IYATT-yx** [comment]
都试过的，另外，DHCP 不管选哪一种，都一样的效果。等会我再看看

**Comment by Rain021300** [comment]
行，你可以再试试

**Comment by Rain021300** [comment]
看到了你今天的博客，启动项预置，在 package/base-files/files/etc/rc.local 添加  这里能不能添加ua2f的启动命令呢？还是只能添加ipid的？

**Comment by IYATT-yx** [comment]
UA2F 本身写了启动脚本的，只需要用 service 命令设置一下就行。lede 源码里 package/lean/default-settings/files/zzz-default-settings 可以设置默认配置，我就把 UA2F 的相关配置写在里面了，刷好固件首次启动就生效。

**Comment by Rain021300** [comment]
> UA2F 本身写了启动脚本的，只需要用 service 命令设置一下就行。lede 源码里 package/lean/default-settings/files/zzz-default-settings 可以设置默认配置，我就把 UA2F 的相关配置写在里面了，刷好固件首次启动就生效。

把ua2f的设置命令填写到zzz-default-settings就可以了吗？那下次重启后还会生效吗？

**Comment by IYATT-yx** [comment]
> > UA2F 本身写了启动脚本的，只需要用 service 命令设置一下就行。lede 源码里 package/lean/default-settings/files/zzz-default-settings 可以设置默认配置，我就把 UA2F 的相关配置写在里面了，刷好固件首次启动就生效。
> 
> 把ua2f的设置命令填写到zzz-default-settings就可以了吗？那下次重启后还会生效吗？

刷固件后第一次启动才执行，或者你重置之后启动也会自动执行一次。就相当于是给固件添加的默认设置，就比如 openwrt 本身是没设置管理页面密码的，lede 就在这个文件里面加了修改 /etc/shadow 文件的命令，把密码改为 password。我习惯了不用密码，所以把 lede 的这一条配置注释了，编译出来的固件进管理又变回没密码了。

**Comment by IYATT-yx** [comment]
UA2F 作者写了启动脚本，只需要执行 service 设置自启动，不需要添加到启动项也能开机自启动

**Comment by Rain021300** [comment]
> UA2F 作者写了启动脚本，只需要执行 service 设置自启动，不需要添加到启动项也能开启自启动

ua2f的配置呢，你使用的是默认的配置还是自己手动配置的呢？

**Comment by IYATT-yx** [comment]
> > UA2F 作者写了启动脚本，只需要执行 service 设置自启动，不需要添加到启动项也能开启自启动
> 
> ua2f的配置呢，你使用的是默认的配置还是自己手动配置的呢？

就是添加到 zzz-default-settings 里的内容：

`# 开机自启
uci set ua2f.enabled.enabled=1
\# 自动配置防火墙（默认开启）（建议开启）  
uci set ua2f.firewall.handle_fw=1  
\# 处理内网流量（默认开启），防止在访问内网服务时被检测到。（建议开启）
uci set ua2f.firewall.handle_intranet=1
\# 处理 443 端口流量（默认关闭），443 端口出现 http 流量的概率较低
uci set ua2f.firewall.handle_tls=1
\# 处理微信的 mmtls（默认开启）（建议关闭）
uci set ua2f.firewall.handle_mmtls=1
\# 提交上面设置
uci commit ua2f
\# 添加 ua2f 服务自启
service ua2f enable
# 启动 ua2f 服务
service ua2f start`

**Comment by IYATT-yx** [comment]
对了，还有一种思路。我测试过我们学校的，UDP 53 端口没封，在校外搭建一个 VPN 服务器，校内网代理过去就能上网，宽带账号都不需要。

**Comment by Rain021300** [comment]
我在看你日志的时候发现了，但是租用vps想要达到高带宽非常贵，如果在家里远程使用小型服务器来搞的还合适一点，但是要考虑上下行以及公网ip、运营商封禁、意外断电等问题，这条路不太建议。

**Comment by Rain021300** [comment]
除了mentohust还有minieap可以认证锐捷，并且好像支持高版本，我觉得你可以去研究一下那个，并且issues里有相关讨论，但是我了解的不多，也看不懂他们在讨论什么。。。

**Comment by Rain021300** [comment]
你有没有试过在mentohust设置dns来解决可以上qq不能打开网页的问题？

**Comment by IYATT-yx** [comment]
> 除了mentohust还有minieap可以认证锐捷，并且好像支持高版本，我觉得你可以去研究一下那个，并且issues里有相关讨论，但是我了解的不多，也看不懂他们在讨论什么。。。

emmm，差不多，我也不是计科的，有很多都不太懂，深入又得花不少时间。再加上我大四，也快离开了，没必要去折腾了

**Comment by IYATT-yx** [comment]
> 你有没有试过在mentohust设置dns来解决可以上qq不能打开网页的问题？

试过，没解决。应该不是 DNS 得问题，ping 的时候都有数据

**Comment by Rain021300** [comment]
> > 你有没有试过在mentohust设置dns来解决可以上qq不能打开网页的问题？
> 
> 试过，没解决。应该不是 DNS 得问题，ping 的时候都有数据

有可能是判断service的问题，具体我也不清楚，但是能ping通按道理来说应该有网的。如果清楚检测机制直接避开检测使用web登录不使用插件也可以，这方面我懂的也非常少，爱莫能助了。我今年毕业同时专升本新生，你要考研吗还是直接工作。

**Comment by Rain021300** [comment]
有没有试过openclash加密？

**Comment by IYATT-yx** [comment]
> 有没有试过openclash加密？

openclash 就是走代理，需要一个校外的服务器作为代理点，在校内和校外服务器之间构建一条 VPN 通道。速度受服务器带宽影响，这样搞不如 DNS 隧道，直接绕过认证页面。

**Comment by IYATT-yx** [comment]
> 有没有试过openclash加密？

就类似把魔法上网客户端搬到路由器上，只要连路由器的设备就可以魔法上网。不过这里用境外服务器延时可能会比较高，换成国内的，搭建一个节点就行。所有经过路由器的数据都加密发送到节点服务器，经过服务器代理访问 Internet。

**Comment by Rain021300** [comment]
【路由器代替锐捷认证校园网-哔哩哔哩】 https://b23.tv/0gBwAi0


可以试试视频后边抓包上传，视频里博主也是选择服务商，我觉得你可以试一下。

**Comment by IYATT-yx** [comment]
> 【路由器代替锐捷认证校园网-哔哩哔哩】 https://b23.tv/0gBwAi0
> 
> 可以试试视频后边抓包上传，视频里博主也是选择服务商，我觉得你可以试一下。

视频中的抓包工具不适用在这里的网页认证，网页认证的抓包用浏览器的调试工具就能做到，不是不知道该写成什么格式才能被 MentiHUST 使用。暂时我要放一放了，没多少精力继续搞。

**Comment by IYATT-yx** [comment]
> > 【路由器代替锐捷认证校园网-哔哩哔哩】 https://b23.tv/0gBwAi0
> > 可以试试视频后边抓包上传，视频里博主也是选择服务商，我觉得你可以试一下。
> 
> 视频中的抓包工具不适用在这里的网页认证，网页认证的抓包用浏览器的调试工具就能做到，只是不知道该写成什么格式才能被 MentiHUST 使用。暂时我要放一放了，没多少精力继续搞。
