### ISSUE TITLE
newifi3无线老是断会是个啥问题呢？

### ISSUE THREAD

**Issue by unknownartist7** [IYATT-yx/Router#4]
Wed May 31 15:29:07 2023 daemon.info hostapd: wlan0: STA 64:a2:00:58:14:30 IEEE 802.11: associated (aid 2)
Wed May 31 15:29:07 2023 daemon.notice hostapd: wlan0: AP-STA-CONNECTED 64:a2:00:58:14:30
Wed May 31 15:29:07 2023 daemon.info hostapd: wlan0: STA 64:a2:00:58:14:30 WPA: pairwise key handshake completed (RSN)
Wed May 31 15:29:07 2023 daemon.notice hostapd: wlan0: EAPOL-4WAY-HS-COMPLETED 64:a2:00:58:14:30
Wed May 31 15:29:39 2023 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 64:a2:00:58:14:30
Wed May 31 15:29:39 2023 daemon.notice hostapd: wlan0: STA 64:a2:00:58:14:30 IEEE 802.11: did not acknowledge authentication response
Wed May 31 15:29:39 2023 daemon.info hostapd: wlan0: STA 64:a2:00:58:14:30 IEEE 802.11: associated (aid 2)
Wed May 31 15:29:39 2023 daemon.notice hostapd: wlan0: AP-STA-CONNECTED 64:a2:00:58:14:30
Wed May 31 15:29:39 2023 daemon.info hostapd: wlan0: STA 64:a2:00:58:14:30 WPA: pairwise key handshake completed (RSN)
Wed May 31 15:29:39 2023 daemon.notice hostapd: wlan0: EAPOL-4WAY-HS-COMPLETED 64:a2:00:58:14:30
Wed May 31 15:29:39 2023 daemon.info dnsmasq-dhcp[1]: DHCPDISCOVER(br-lan) 64:a2:00:58:14:30
Wed May 31 15:29:39 2023 daemon.info dnsmasq-dhcp[1]: DHCPOFFER(br-lan) 10.0.0.190 64:a2:00:58:14:30
Wed May 31 15:29:39 2023 daemon.info dnsmasq-dhcp[1]: DHCPREQUEST(br-lan) 10.0.0.190 64:a2:00:58:14:30
Wed May 31 15:29:39 2023 daemon.info dnsmasq-dhcp[1]: DHCPACK(br-lan) 10.0.0.190 64:a2:00:58:14:30 M2002J9E-woyoulongju
Wed May 31 15:30:06 2023 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 64:a2:00:58:14:30
Wed May 31 15:30:06 2023 daemon.info hostapd: wlan0: STA 64:a2:00:58:14:30 IEEE 802.11: authenticated
Wed May 31 15:30:06 2023 daemon.info hostapd: wlan0: STA 64:a2:00:58:14:30 IEEE 802.11: associated (aid 2)
Wed May 31 15:30:06 2023 daemon.notice hostapd: wlan0: AP-STA-CONNECTED 64:a2:00:58:14:30
Wed May 31 15:30:06 2023 daemon.info hostapd: wlan0: STA 64:a2:00:58:14:30 WPA: pairwise key handshake completed (RSN)
Wed May 31 15:30:06 2023 daemon.notice hostapd: wlan0: EAPOL-4WAY-HS-COMPLETED 64:a2:00:58:14:30
Wed May 31 15:30:06 2023 daemon.info dnsmasq-dhcp[1]: DHCPDISCOVER(br-lan) 64:a2:00:58:14:30
Wed May 31 15:30:06 2023 daemon.info dnsmasq-dhcp[1]: DHCPOFFER(br-lan) 10.0.0.190 64:a2:00:58:14:30
Wed May 31 15:30:06 2023 daemon.info dnsmasq-dhcp[1]: DHCPREQUEST(br-lan) 10.0.0.190 64:a2:00:58:14:30
Wed May 31 15:30:06 2023 daemon.info dnsmasq-dhcp[1]: DHCPACK(br-lan) 10.0.0.190 64:a2:00:58:14:30 M2002J9E-woyoulongju
Wed May 31 15:30:15 2023 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 64:a2:00:58:14:30
Wed May 31 15:30:25 2023 daemon.notice hostapd: wlan0: STA 64:a2:00:58:14:30 IEEE 802.11: did not acknowledge authentication response
Wed May 31 15:30:25 2023 daemon.info hostapd: wlan0: STA 64:a2:00:58:14:30 IEEE 802.11: associated (aid 1)
Wed May 31 15:30:25 2023 daemon.notice hostapd: wlan0: AP-STA-CONNECTED 64:a2:00:58:14:30
Wed May 31 15:30:25 2023 daemon.info hostapd: wlan0: STA 64:a2:00:58:14:30 WPA: pairwise key handshake completed (RSN)
Wed May 31 15:30:25 2023 daemon.notice hostapd: wlan0: EAPOL-4WAY-HS-COMPLETED 64:a2:00:58:14:30
Wed May 31 15:30:25 2023 daemon.info dnsmasq-dhcp[1]: DHCPDISCOVER(br-lan) 64:a2:00:58:14:30
Wed May 31 15:30:25 2023 daemon.info dnsmasq-dhcp[1]: DHCPOFFER(br-lan) 10.0.0.190 64:a2:00:58:14:30
Wed May 31 15:30:25 2023 daemon.info dnsmasq-dhcp[1]: DHCPREQUEST(br-lan) 10.0.0.190 64:a2:00:58:14:30
Wed May 31 15:30:25 2023 daemon.info dnsmasq-dhcp[1]: DHCPACK(br-lan) 10.0.0.190 64:a2:00:58:14:30 M2002J9E-woyoulongju
Wed May 31 15:33:04 2023 user.info mwan3track[1930]: Check (ping) failed for target "8.8.8.8" on interface wan (wan). Current score: 10
Wed May 31 15:35:53 2023 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 64:a2:00:58:14:30
Wed May 31 15:35:53 2023 daemon.info hostapd: wlan0: STA 64:a2:00:58:14:30 IEEE 802.11: disassociated due to inactivity
Wed May 31 15:35:54 2023 daemon.info hostapd: wlan0: STA 64:a2:00:58:14:30 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Wed May 31 15:36:01 2023 user.info mwan3track[1930]: Check (ping) failed for target "8.8.4.4" on interface wan (wan). Current score: 10
Wed May 31 15:36:05 2023 user.info mwan3track[1930]: Check (ping) failed for target "8.8.8.8" on interface wan (wan). Current score: 10
Wed May 31 15:38:11 2023 user.info mwan3track[1930]: Check (ping) failed for target "8.8.4.4" on interface wan (wan). Current score: 10
Wed May 31 15:40:17 2023 user.info mwan3track[1930]: Check (ping) failed for target "8.8.4.4" on interface wan (wan). Current score: 10
Wed May 31 15:43:03 2023 user.info mwan3track[1930]: Check (ping) failed for target "8.8.4.4" on interface wan (wan). Current score: 10
Wed May 31 15:47:32 2023 user.info mwan3track[

Wed May 31 15:30:06 2023 daemon.info dnsmasq-dhcp[1]: DHCPACK(br-lan) 10.0.0.190 64:a2:00:58:14:30 M2002J9E-woyoulongju
Wed May 31 15:30:15 2023 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 64:a2:00:58:14:30
Wed May 31 15:30:25 2023 daemon.notice hostapd: wlan0: STA 64:a2:00:58:14:30 IEEE 802.11: did not acknowledge authentication response
Wed May 31 15:30:25 2023 daemon.info hostapd: wlan0: STA 64:a2:00:58:14:30 IEEE 802.11: associated (aid 1)
Wed May 31 15:30:25 2023 daemon.notice hostapd: wlan0: AP-STA-CONNECTED 64:a2:00:58:14:30
Wed May 31 15:30:25 2023 daemon.info hostapd: wlan0: STA 64:a2:00:58:14:30 WPA: pairwise key handshake completed (RSN)
Wed May 31 15:30:25 2023 daemon.notice hostapd: wlan0: EAPOL-4WAY-HS-COMPLETED 64:a2:00:58:14:30
Wed May 31 15:30:25 2023 daemon.info dnsmasq-dhcp[1]: DHCPDISCOVER(br-lan) 64:a2:00:58:14:30
Wed May 31 15:30:25 2023 daemon.info dnsmasq-dhcp[1]: DHCPOFFER(br-lan) 10.0.0.190 64:a2:00:58:14:30
Wed May 31 15:30:25 2023 daemon.info dnsmasq-dhcp[1]: DHCPREQUEST(br-lan) 10.0.0.190 64:a2:00:58:14:30
Wed May 31 15:30:25 2023 daemon.info dnsmasq-dhcp[1]: DHCPACK(br-lan) 10.0.0.190 64:a2:00:58:14:30 M2002J9E-woyoulongju
Wed May 31 15:33:04 2023 user.info mwan3track[1930]: Check (ping) failed for target "8.8.8.8" on interface wan (wan). Current score: 10
Wed May 31 15:35:53 2023 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 64:a2:00:58:14:30
Wed May 31 15:35:53 2023 daemon.info hostapd: wlan0: STA 64:a2:00:58:14:30 IEEE 802.11: disassociated due to inactivity
Wed May 31 15:35:54 2023 daemon.info hostapd: wlan0: STA 64:a2:00:58:14:30 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Wed May 31 15:36:01 2023 user.info mwan3track[1930]: Check (ping) failed for target "8.8.4.4" on interface wan (wan). Current score: 10
Wed May 31 15:36:05 2023 user.info mwan3track[1930]: Check (ping) failed for target "8.8.8.8" on interface wan (wan). Current score: 10
Wed May 31 15:38:11 2023 user.info mwan3track[1930]: Check (ping) failed for target "8.8.4.4" on interface wan (wan). Current score: 10
Wed May 31 15:40:17 2023 user.info mwan3track[1930]: Check (ping) failed for target "8.8.4.4" on interface wan (wan). Current score: 10
Wed May 31 15:43:03 2023 user.info mwan3track[1930]: Check (ping) failed for target "8.8.4.4" on interface wan (wan). Current score: 10
Wed May 31 15:47:32 2023 user.info mwan3track[1930]: Check (ping) failed for target "8.8.4.4" on interface wan (wan). Current score: 10
Wed May 31 15:50:39 2023 user.info mwan3track[1930]: Check (ping) failed for target "8.8.4.4" on interface wan (wan). Current score: 10
Wed May 31 15:50:53 2023 user.info mwan3track[1930]: Check (ping) failed for target "8.8.4.4" on interface wan (wan). Current score: 10
Wed May 31 15:55:28 2023 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED a2:a8:8c:f9:07:aa

**Comment by IYATT-yx** [comment]
我看你日志里面有出现验证失败中断连接（密码错误，加密设置配置不当，距离超出或者信号弱），以及设备长时间不活动中断连接（比较可能是手机省电设置，休眠时断开WiFi），提供的信息有限，我也不能有效判断
